import React from 'react';
import { BookOpen, Network, Brain, ArrowRight, Sparkles } from 'lucide-react';

/**
 * WelcomeScreen - Epistemic disclaimer on app start
 * Explains how the Hybrid RAG System works
 */
export default function WelcomeScreen({ onDismiss }) {
  return (
    <div className="fixed inset-0 bg-gradient-to-br from-slate-900 via-indigo-900 to-slate-900 flex items-center justify-center p-6 z-50">
      <div className="max-w-2xl w-full">
        {/* Logo/Title */}
        <div className="text-center mb-10">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-white/10 backdrop-blur mb-6">
            <Sparkles className="w-8 h-8 text-indigo-300" />
          </div>
          <h1 className="text-4xl font-bold text-white mb-3">
            AI Knowledge Platform
          </h1>
          <p className="text-lg text-indigo-200">
            Hybrid RAG System for Scientific Literature
          </p>
        </div>

        {/* Epistemic Notes */}
        <div className="space-y-4 mb-10">
          {/* Relational Search */}
          <div className="bg-white/5 backdrop-blur border border-white/10 rounded-xl p-5">
            <div className="flex items-start space-x-4">
              <div className="flex-shrink-0 w-10 h-10 rounded-lg bg-emerald-500/20 flex items-center justify-center">
                <Network className="w-5 h-5 text-emerald-400" />
              </div>
              <div>
                <h3 className="text-white font-semibold mb-1">Knowledge Graph (Neo4j)</h3>
                <p className="text-sm text-gray-300">
                  Shows <span className="text-emerald-400 font-medium">explicit connections</span> between
                  papers: shared authors, citations, institutions.
                  These facts are verifiable and objective.
                </p>
              </div>
            </div>
          </div>

          {/* Semantic Search */}
          <div className="bg-white/5 backdrop-blur border border-white/10 rounded-xl p-5">
            <div className="flex items-start space-x-4">
              <div className="flex-shrink-0 w-10 h-10 rounded-lg bg-indigo-500/20 flex items-center justify-center">
                <Brain className="w-5 h-5 text-indigo-400" />
              </div>
              <div>
                <h3 className="text-white font-semibold mb-1">Semantic Search (Vector DB)</h3>
                <p className="text-sm text-gray-300">
                  Finds <span className="text-indigo-400 font-medium">content-similar</span> papers
                  based on text embeddings. These similarities are
                  AI-interpreted and may vary.
                </p>
              </div>
            </div>
          </div>

          {/* LLM Answers */}
          <div className="bg-white/5 backdrop-blur border border-white/10 rounded-xl p-5">
            <div className="flex items-start space-x-4">
              <div className="flex-shrink-0 w-10 h-10 rounded-lg bg-amber-500/20 flex items-center justify-center">
                <BookOpen className="w-5 h-5 text-amber-400" />
              </div>
              <div>
                <h3 className="text-white font-semibold mb-1">AI-Generated Answers</h3>
                <p className="text-sm text-gray-300">
                  Answers are generated by an LLM and may contain
                  <span className="text-amber-400 font-medium"> inaccuracies</span>.
                  Sources are cited with [1], [2] - always verify them.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Transparency Note */}
        <div className="text-center mb-8">
          <p className="text-sm text-gray-400">
            This system transparently shows where information comes from.
            <br />
            Don't trust blindly - verify critical statements.
          </p>
        </div>

        {/* Start Button */}
        <div className="text-center">
          <button
            onClick={onDismiss}
            className="inline-flex items-center px-8 py-4 bg-white text-slate-900 rounded-xl font-semibold text-lg hover:bg-indigo-100 transition-all shadow-lg hover:shadow-xl transform hover:-translate-y-0.5"
          >
            Got it, continue to app
            <ArrowRight className="w-5 h-5 ml-2" />
          </button>
        </div>

        {/* Footer */}
        <p className="text-center text-xs text-gray-500 mt-8">
          AI Knowledge Platform v1.0 - Epistemically transparent literature research
        </p>
      </div>
    </div>
  );
}
